export const ADD_CONTACTS = "ADD_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const UPDATE_PARAMS = "UPDATE_PARAMS";
